version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: test
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.4
  - dependency-name: Microsoft.Azure.WebJobs.Extensions.DurableTask
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: Microsoft.Azure.Management.Fluent
    versions:
    - 1.37.0
    - 1.37.1
  - dependency-name: nunit
    versions:
    - 3.13.1
